// ==========================================================================
// NIGHT-SYSTEM | MASTER FEATURES CATALOG (EXAKT 250 FEATURES)
// Modularer Funktionskatalog | Kategorisiert | Durchsuchbar | Favorisierbar
// Keine Emojis | Praezise Abkuerzungen | Robuste Fehlerbehandlung
// ==========================================================================

const MASTER_FEATURES_CATALOG = [
  // ------------------------------------------------------------------------
  // KATEGORIE 1: HWID & SICHERHEIT (25 FEATURES: F-001 bis F-025)
  // ------------------------------------------------------------------------
  { id: 'F-001', name: 'HWID Hardware-Sperre', cat: 'security', desc: 'Sperrt ein Zielgeraet dauerhaft anhand seiner eindeutigen Hardware-ID.', type: 'security', action: 'ban_hwid' },
  { id: 'F-002', name: 'HWID Freigabe / Entbannen', cat: 'security', desc: 'Hebt eine bestehende HWID-Sperre auf und gestattet erneuten Zugriff.', type: 'security', action: 'unban_hwid' },
  { id: 'F-003', name: 'IP-Adressen Validierung', cat: 'security', desc: 'Prueft Client-IP auf Subnetz-Zugehoerigkeit, Proxy- und VPN-Merkmale.', type: 'diagnostic', action: 'check_ip' },
  { id: 'F-004', name: 'HWID Hash-Fingerprinting', cat: 'security', desc: 'Berechnet kryptografischen SHA-256 Fingerprint ueber CPU & Display.', type: 'tool', action: 'fingerprint_hwid' },
  { id: 'F-005', name: 'Sitzungs-Widerruf', cat: 'security', desc: 'Widerruft alle aktiven Client-Tokens und erzwingt Neu-Authentifizierung.', type: 'remote', action: 'session_disconnect' },
  { id: 'F-006', name: 'Admin-PIN Validierung', cat: 'security', desc: 'Verifiziert die Berechtigungsstufe der aktuellen Admin-Sitzung.', type: 'security', action: 'verify_admin' },
  { id: 'F-007', name: 'Integritaets-Waechter', cat: 'security', desc: 'Prueft Skriptdateien des Clients auf unautorisierte Aenderungen.', type: 'diagnostic', action: 'integrity_scan' },
  { id: 'F-008', name: 'Zwei-Faktor Schutzstatus', cat: 'security', desc: 'Prueft Sicherheitsstatus und Schutzrichtlinien des Web-Dashboards.', type: 'security', action: 'check_2fa' },
  { id: 'F-009', name: 'API Rate-Limit Regel', cat: 'security', desc: 'Schuetzt Server-Endpunkte vor uebermaessiger Abfragefrequenz.', type: 'security', action: 'rate_limit_rule' },
  { id: 'F-010', name: 'Session-Key Rotation', cat: 'security', desc: 'Erneuert temporaere Sitzungsschluessel fuer die Client-Kommunikation.', type: 'security', action: 'rotate_keys' },
  { id: 'F-011', name: 'Zugriffsrechte-Matrix', cat: 'security', desc: 'Visualisiert Rollen und Berechtigungen aller aktiven Instanzen.', type: 'tool', action: 'permissions_matrix' },
  { id: 'F-012', name: 'Audit Notfallprotokoll', cat: 'security', desc: 'Erzeugt sofortigen Snapshot aller aktuellen Sicherheitsereignisse.', type: 'tool', action: 'emergency_audit' },
  { id: 'F-013', name: 'Geo-IP Indikator', cat: 'security', desc: 'Ermittelt geografischen Ursprungsknoten und Latenz-Routing der Clients.', type: 'diagnostic', action: 'geo_ip' },
  { id: 'F-014', name: 'HWID Anomaly Detector', cat: 'security', desc: 'Erkennt Unstimmigkeiten zwischen Hardware-ID und gemeldetem Hostnamen.', type: 'diagnostic', action: 'hwid_anomaly' },
  { id: 'F-015', name: 'Client-Quarantaene Modus', cat: 'security', desc: 'Isoliert verdaechtige Clients temporaer ohne dauerhaften Bann.', type: 'remote', action: 'quarantine_client' },
  { id: 'F-016', name: 'Krypto Keypair Generator', cat: 'security', desc: 'Generiert kryptografische RSA/Ed25519 Schluesselpaare im Browser.', type: 'tool', action: 'generate_keypair' },
  { id: 'F-017', name: 'SSL/TLS Header Enforcer', cat: 'security', desc: 'Validiert HTTPS-Verschluesselung und prueft Security-Header.', type: 'diagnostic', action: 'tls_check' },
  { id: 'F-018', name: 'Heartbeat Guard Dog', cat: 'security', desc: 'Schlaegt Alarm bei unerwartetem Ausbleiben von Lebenszeichen.', type: 'tool', action: 'guard_dog' },
  { id: 'F-019', name: 'Killswitch Notaus-Sim', cat: 'security', desc: 'Testet die sofortige weltweite Sperrfunktion im sicheren Sandbox-Modus.', type: 'tool', action: 'sim_killswitch' },
  { id: 'F-020', name: 'Sicherheits-Audit Export', cat: 'security', desc: 'Exportiert alle relevanten Sicherheitsereignisse als signierte Datei.', type: 'tool', action: 'export_security' },
  { id: 'F-021', name: 'Client Sandbox Pruefer', cat: 'security', desc: 'Testet Berechtigungsumfang und Isolationsgrad der Client-Umgebung.', type: 'diagnostic', action: 'sandbox_check' },
  { id: 'F-022', name: 'Identitaets-Verifizierer', cat: 'security', desc: 'Gleicht Hostname, Benutzerkonto und Systemplattform plausibel ab.', type: 'diagnostic', action: 'verify_identity' },
  { id: 'F-023', name: 'Brute-Force Abwehr', cat: 'security', desc: 'Zeigt Haeufigkeit abgelehnter Zugriffe und IP-Sperrlisten.', type: 'security', action: 'bruteforce_monitor' },
  { id: 'F-024', name: 'Device Trust Score', cat: 'security', desc: 'Berechnet Vertrauens-Score (0 bis 100) basierend auf System-Historie.', type: 'diagnostic', action: 'trust_score' },
  { id: 'F-025', name: 'CSP Header Auditor', cat: 'security', desc: 'Validiert Content-Security-Policy gegen Code-Injection und XSS.', type: 'security', action: 'csp_audit' },

  // ------------------------------------------------------------------------
  // KATEGORIE 2: SYSTEM & WARTUNG (30 FEATURES: F-026 bis F-055)
  // ------------------------------------------------------------------------
  { id: 'F-026', name: 'Downgrade auf v1.0.0', cat: 'system', desc: 'Stuft Client remote zurueck und erzwingt das Update-Overlay.', type: 'remote', action: 'downgrade_v100' },
  { id: 'F-027', name: 'Downgrade auf v0.9.0', cat: 'system', desc: 'Stuft Client remote auf Legacy-Version v0.9.0 zurueck.', type: 'remote', action: 'downgrade_v090' },
  { id: 'F-028', name: 'Wunsch-Version Setter', cat: 'system', desc: 'Setzt installierte Client-Version remote auf frei waehlbaren Wert.', type: 'remote', action: 'set_custom_version' },
  { id: 'F-029', name: 'Cache Purge & Reload', cat: 'system', desc: 'Bereinigt lokalen Client-Cache und fuehrt sauberen Neustart aus.', type: 'remote', action: 'cache_clear_reload' },
  { id: 'F-030', name: 'LocalStorage Reset', cat: 'system', desc: 'Entleert clientseitigen persistenten Web-Speicher restlos.', type: 'remote', action: 'reset_localstorage' },
  { id: 'F-031', name: 'SessionStorage Reset', cat: 'system', desc: 'Bereinigt aktive Sitzungsdaten und initialisiert Variablen neu.', type: 'remote', action: 'reset_sessionstorage' },
  { id: 'F-032', name: 'WhatsApp Abmeldung', cat: 'system', desc: 'Trennt WhatsApp-Web Sitzung remote fuer sauberen Neuanfang.', type: 'remote', action: 'session_disconnect' },
  { id: 'F-033', name: 'QR-Code Erneuerung', cat: 'system', desc: 'Fordert sofortige Neugenerierung des WhatsApp Login-QRs an.', type: 'remote', action: 'qr_force_rotate' },
  { id: 'F-034', name: 'UI Force Reload', cat: 'system', desc: 'Laedt die gesamte Client-Oberflaeche remote neu.', type: 'remote', action: 'force_reload' },
  { id: 'F-035', name: 'Tool Prozess-Shutdown', cat: 'system', desc: 'Beendet den Hintergrundprozess des WhatsApp-Tools beim Client.', type: 'remote', action: 'force_close' },
  { id: 'F-036', name: 'Garbage Collector Run', cat: 'system', desc: 'Triggert manuelle V8-Speicherbereinigung im Server-Prozess.', type: 'tool', action: 'run_gc' },
  { id: 'F-037', name: 'DOM Node Sweeper', cat: 'system', desc: 'Entfernt nicht mehr benoetigte verwaiste Elemente aus dem Dokument.', type: 'tool', action: 'sweep_dom' },
  { id: 'F-038', name: 'Service Worker Refresh', cat: 'system', desc: 'Aktualisiert registrierte Hintergrund-Worker auf den neuesten Stand.', type: 'tool', action: 'refresh_sw' },
  { id: 'F-039', name: 'Cache Storage Eviction', cat: 'system', desc: 'Entleert temporaere Bild- und Mediendateien aus dem Cache.', type: 'tool', action: 'evict_cache' },
  { id: 'F-040', name: 'IndexedDB Compact', cat: 'system', desc: 'Fuehrt Optimierung und Indexierung lokaler Datenbanken durch.', type: 'tool', action: 'compact_idb' },
  { id: 'F-041', name: 'Session Snapshot Backup', cat: 'system', desc: 'Erstellt Momentaufnahme aller aktuellen App-Einstellungen.', type: 'tool', action: 'backup_session' },
  { id: 'F-042', name: 'Werkseinstellungen Reset', cat: 'system', desc: 'Setzt UI-Konfiguration und Dashboard auf Standardwerte.', type: 'tool', action: 'reset_config' },
  { id: 'F-043', name: 'Port Ping Tester', cat: 'system', desc: 'Ueberprueft lokale Portverfuegbarkeit und Server-Bindung.', type: 'diagnostic', action: 'ping_port' },
  { id: 'F-044', name: 'Prozess Heartbeat Monitor', cat: 'system', desc: 'Kontrolliert Uptime und Zykluszeit des Server-Prozesses.', type: 'diagnostic', action: 'process_heartbeat' },
  { id: 'F-045', name: 'Telemetrie Puffer Flush', cat: 'system', desc: 'Sendet alle anstehenden Telemetriedaten unmittelbar ab.', type: 'tool', action: 'flush_telemetry' },
  { id: 'F-046', name: 'Cloud Sync State Force', cat: 'system', desc: 'Gleicht den Zustand sofort mit dem zentralen Render-Server ab.', type: 'tool', action: 'force_cloud_sync' },
  { id: 'F-047', name: 'Cluster Node Beacon', cat: 'system', desc: 'Sendet Erkennungs-Beacon an alle verbundenen Dashboard-Knoten.', type: 'tool', action: 'send_beacon' },
  { id: 'F-048', name: 'Fallback Host Umschaltung', cat: 'system', desc: 'Konfiguriert alternativen Fallback-Server fuer Ausfallszenarien.', type: 'tool', action: 'switch_fallback' },
  { id: 'F-049', name: 'Wartungsmodus Bypass', cat: 'system', desc: 'Gestattet autorisierten Administratoren Zugriff bei aktivem Lock.', type: 'security', action: 'bypass_maintenance' },
  { id: 'F-050', name: 'Client Auto-Restart Timer', cat: 'system', desc: 'Programmiert einen zeitgesteuerten Neustart der Client-App.', type: 'tool', action: 'timer_restart' },
  { id: 'F-051', name: 'Speicher-Quota Auditor', cat: 'system', desc: 'Ermittelt verfuegbaren und genutzten HTML5 Quota-Speicher.', type: 'diagnostic', action: 'check_quota' },
  { id: 'F-052', name: 'DB Integritaetspruefung', cat: 'system', desc: 'Validiert Struktur und Konsistenz lokaler JSON-Datensaetze.', type: 'diagnostic', action: 'validate_db' },
  { id: 'F-053', name: 'Node Environment Dump', cat: 'system', desc: 'Prueft aktive Node-Umgebung und relevante Laufzeit-Flags.', type: 'diagnostic', action: 'dump_env' },
  { id: 'F-054', name: 'Boot Profiler Zeitmesser', cat: 'system', desc: 'Analysiert Boot- und Ladezeiten einzelner Initialisierungsphasen.', type: 'diagnostic', action: 'boot_profile' },
  { id: 'F-055', name: 'Server Uptime Tracker', cat: 'system', desc: 'Praezise Anzeige der Betriebsdauer seit letztem Start.', type: 'diagnostic', action: 'uptime_tracker' },

  // ------------------------------------------------------------------------
  // KATEGORIE 3: NETZWERK & TELEMETRIE (25 FEATURES: F-056 bis F-080)
  // ------------------------------------------------------------------------
  { id: 'F-056', name: 'Live Ping Latenz-Graph', cat: 'network', desc: 'Misst und visualisiert RTT-Latenzen zum zentralen Server in Echtzeit.', type: 'diagnostic', action: 'ping_graph' },
  { id: 'F-057', name: 'Response Header Inspector', cat: 'network', desc: 'Zeigt alle HTTP-Antwortheader der Cloud-Verbindung detailliert an.', type: 'diagnostic', action: 'inspect_headers' },
  { id: 'F-058', name: 'Webhook Test Dispatcher', cat: 'network', desc: 'Sendet formatierten Test-Datensatz an konfigurierten Webhook.', type: 'tool', action: 'test_webhook' },
  { id: 'F-059', name: 'DNS Resolve Simulator', cat: 'network', desc: 'Ueberprueft Aufloesung von Domainnamen und Render-Endpunkten.', type: 'diagnostic', action: 'dns_sim' },
  { id: 'F-060', name: 'Payload Size Meter', cat: 'network', desc: 'Berechnet exakte Byte-Groesse gesendeter und empfangener Daten.', type: 'diagnostic', action: 'payload_meter' },
  { id: 'F-061', name: 'Bandbreiten-Schaetzer', cat: 'network', desc: 'Ermittelt ungefaehre Download-Geschwindigkeit zum Cloud-Server.', type: 'diagnostic', action: 'bandwidth_test' },
  { id: 'F-062', name: 'Jitter Estimator', cat: 'network', desc: 'Misst statistische Latenzschwankungen zwischen mehreren Pings.', type: 'diagnostic', action: 'jitter_calc' },
  { id: 'F-063', name: 'Stream Status Monitor', cat: 'network', desc: 'Ueberprueft Aktivitaet persistenter VerbindungsKanaele.', type: 'diagnostic', action: 'stream_monitor' },
  { id: 'F-064', name: 'Offline Modus Tester', cat: 'network', desc: 'Simuliert temporaeren Netzwerkausfall zur UI-Reaktionspruefung.', type: 'tool', action: 'sim_offline' },
  { id: 'F-065', name: 'Cloud Endpoint Switcher', cat: 'network', desc: 'Schaltet flexibel zwischen Primaer- und Ausweich-Endpunkt um.', type: 'tool', action: 'switch_endpoint' },
  { id: 'F-066', name: 'CDN Route Verifier', cat: 'network', desc: 'Prueft Edge-Server Routing und Cloudflare/Render Zwischenknoten.', type: 'diagnostic', action: 'route_verifier' },
  { id: 'F-067', name: 'Packet Drop Simulator', cat: 'network', desc: 'Simuliert Heartbeat-Paketverluste zur Robustheitstestung.', type: 'tool', action: 'sim_drop' },
  { id: 'F-068', name: 'Reverse Proxy Probe', cat: 'network', desc: 'Erkennt vorgeschaltete Nginx- oder Cloudflare-Proxys anhand Header.', type: 'diagnostic', action: 'proxy_probe' },
  { id: 'F-069', name: 'Route Trace Visualizer', cat: 'network', desc: 'Visualisiert symbolisch den Verbindungspfad zum Server.', type: 'diagnostic', action: 'trace_vis' },
  { id: 'F-070', name: 'Keep-Alive Header Test', cat: 'network', desc: 'Prueft ob TCP-Verbindungen dauerhaft offen gehalten werden.', type: 'diagnostic', action: 'keepalive_test' },
  { id: 'F-071', name: 'TLS Handshake Benchmark', cat: 'network', desc: 'Misst Zeitbedarf fuer SSL/TLS Zertifikatspruefung in Millisekunden.', type: 'diagnostic', action: 'tls_benchmark' },
  { id: 'F-072', name: 'MTU Paket-Sizer', cat: 'network', desc: 'Berechnet optimale JSON-Payload-Groesse fuer fehlerfreien Transfer.', type: 'tool', action: 'mtu_calc' },
  { id: 'F-073', name: 'Broadcast Multicast Sim', cat: 'network', desc: 'Testet gleichzeitige Benachrichtigung aller verbundenen Clients.', type: 'tool', action: 'sim_multicast' },
  { id: 'F-074', name: 'Socket Reconnect Routine', cat: 'network', desc: 'Erzwingt sofortigen Reconnect-Versuch nach Verbindungspause.', type: 'tool', action: 'reconnect_socket' },
  { id: 'F-075', name: 'API Rate Tracker', cat: 'network', desc: 'Zaehlt eingehende und ausgehende API-Aufrufe pro Minute.', type: 'diagnostic', action: 'rate_tracker' },
  { id: 'F-076', name: 'Traffic Burst Tester', cat: 'network', desc: 'Simuliert schnelles Senden von 10 Statusmeldungen hintereinander.', type: 'tool', action: 'traffic_burst' },
  { id: 'F-077', name: 'Central Cloud Sync', cat: 'network', desc: 'Uebertraegt aktuellen Admin-Zustand manuell an die Cloud.', type: 'tool', action: 'cloud_sync_now' },
  { id: 'F-078', name: 'Peer Link Verifier', cat: 'network', desc: 'Prueft direkte lokale Erreichbarkeit des lokalen Node.js Servers.', type: 'diagnostic', action: 'peer_verify' },
  { id: 'F-079', name: 'Host Ping Repeater', cat: 'network', desc: 'Sendet 5 aufeinanderfolgende Pings und gibt Durchschnittswert aus.', type: 'diagnostic', action: 'ping_repeat' },
  { id: 'F-080', name: 'Verbindungsverlust-Alarm', cat: 'network', desc: 'Gibt ein akustisches Signal aus wenn die Serververbindung abreisst.', type: 'tool', action: 'disconnect_alert' },

  // ------------------------------------------------------------------------
  // KATEGORIE 4: AUTOMATION & WORKFLOWS (25 FEATURES: F-081 bis F-105)
  // ------------------------------------------------------------------------
  { id: 'F-081', name: 'Auto-Reload bei Desync', cat: 'automation', desc: 'Laedt den Client automatisch neu wenn Versions-Desync erkannt wird.', type: 'automation', action: 'auto_reload_rule' },
  { id: 'F-082', name: 'Zeitgesteuerte Tool-Sperre', cat: 'automation', desc: 'Plant eine automatische Aktivierung des Killswitch zu bestimmter Zeit.', type: 'automation', action: 'schedule_lock' },
  { id: 'F-083', name: 'Heartbeat Watchdog', cat: 'automation', desc: 'Markiert Clients automatisch als abwesend nach 30s ohne Lebenszeichen.', type: 'automation', action: 'watchdog_rule' },
  { id: 'F-084', name: 'Ankuendigungs-Ablaufuhr', cat: 'automation', desc: 'Loescht Broadcast-Nachrichten automatisch nach vorgegebener Dauer.', type: 'automation', action: 'auto_clear_ann' },
  { id: 'F-085', name: 'Inaktivitaets-Schliesser', cat: 'automation', desc: 'Beendet Client-Tools automatisch nach 2 Stunden Leerlauf.', type: 'automation', action: 'idle_closer' },
  { id: 'F-086', name: 'Fehlversuchs-Zaehler', cat: 'automation', desc: 'Erfasst wiederholte fehlgeschlagene Interaktionen automatisch.', type: 'automation', action: 'failure_counter' },
  { id: 'F-087', name: 'Dynamischer Version Bumper', cat: 'automation', desc: 'Berechnet und erhoeht die SemVer-Patch-Version automatisch.', type: 'automation', action: 'auto_bump_ver' },
  { id: 'F-088', name: 'Automatischer Audit-Snapshot', cat: 'automation', desc: 'Erstellt alle 30 Minuten automatisch einen Audit-Log-Zwischenstand.', type: 'automation', action: 'auto_snapshot' },
  { id: 'F-089', name: 'Versions-Anomalie Alarm', cat: 'automation', desc: 'Schlaegt Alarm wenn ein Client eine unerwartete Versionsnummer meldet.', type: 'automation', action: 'ver_anomaly_alert' },
  { id: 'F-090', name: 'Telemetrie Auto-Archiv', cat: 'automation', desc: 'Archiviert Logs aelter als 24 Stunden in kompakter Form.', type: 'automation', action: 'auto_archive' },
  { id: 'F-091', name: 'Smart Throttle Regel', cat: 'automation', desc: 'Verlaengert Polling-Intervalle automatisch bei hoher Server-Latenz.', type: 'automation', action: 'smart_throttle' },
  { id: 'F-092', name: 'Nachtmodus-Automatik', cat: 'automation', desc: 'Wechselt um 20:00 Uhr automatisch in das Cosmic Neon Dunkeldesign.', type: 'automation', action: 'night_mode_rule' },
  { id: 'F-093', name: 'Client Auto-Freigabe', cat: 'automation', desc: 'Schaltet neue Clients aus bekannten IP-Bereichen automatisch frei.', type: 'automation', action: 'auto_allow_rule' },
  { id: 'F-094', name: 'Auto-Downgrade bei Crash', cat: 'automation', desc: 'Stuft Clients automatisch auf v1.0.0 zurueck falls Syntaxfehler auftreten.', type: 'automation', action: 'crash_downgrade' },
  { id: 'F-095', name: 'Geister-Sitzungs Bereinigung', cat: 'automation', desc: 'Entfernt alte Client-Datensaetze automatisch nach 7 Tagen Inaktivitaet.', type: 'automation', action: 'clean_ghost_sessions' },
  { id: 'F-096', name: 'Periodischer Selbsttest', cat: 'automation', desc: 'Fuehrt alle 10 Minuten einen vollstaendigen Backend-Statuscheck durch.', type: 'automation', action: 'periodic_selftest' },
  { id: 'F-097', name: 'Notfall-Beacon Automation', cat: 'automation', desc: 'Sendet im Notfall mit einem Klick Warnung und sperrt alle Clients.', type: 'automation', action: 'emergency_beacon' },
  { id: 'F-098', name: 'Webhook Event Dispatch', cat: 'automation', desc: 'Verschickt Benachrichtigungen bei Lock/Unlock automatisch.', type: 'automation', action: 'webhook_automation' },
  { id: 'F-099', name: 'Auto-Sync Poller Guard', cat: 'automation', desc: 'Ueberwacht den Hintergrund-Polling-Timer auf kontinuierlichen Lauf.', type: 'automation', action: 'poll_guard' },
  { id: 'F-100', name: 'Befehls-Warteschlangen Drain', cat: 'automation', desc: 'Stellt sicher, dass anstehende Befehle schnell verarbeitet werden.', type: 'automation', action: 'drain_cmd_queue' },
  { id: 'F-101', name: 'Client Ping Automatik', cat: 'automation', desc: 'Sendet alle 60 Sekunden einen unscheinbaren Diagnose-Ping.', type: 'automation', action: 'auto_ping_loop' },
  { id: 'F-102', name: 'Speicher-Grenzwert Alarm', cat: 'automation', desc: 'Benachrichtigt den Admin sobald Storage 80% Fuelle erreicht.', type: 'automation', action: 'storage_alert' },
  { id: 'F-103', name: 'Support-Call Schutzregel', cat: 'automation', desc: 'Blockiert automatisiert missbraeuchliche Anrufversuche an Support.', type: 'automation', action: 'protect_support' },
  { id: 'F-104', name: 'Speicherleck Fruehwarnung', cat: 'automation', desc: 'Erkennt ungewoehnlich schnell wachsenden JavaScript-Heap.', type: 'automation', action: 'leak_detector' },
  { id: 'F-105', name: 'Sequentieller Workflow Runner', cat: 'automation', desc: 'Fuehrt eine Kette mehrerer Diagnose- und Wartungsbefehle nacheinander aus.', type: 'automation', action: 'workflow_runner' },

  // ------------------------------------------------------------------------
  // KATEGORIE 5: DIAGNOSE & PERFORMANCE (25 FEATURES: F-106 bis F-130)
  // ------------------------------------------------------------------------
  { id: 'F-106', name: 'Virtuelle CPU Lastanzeige', cat: 'diagnostics', desc: 'Ermittelt geschaetzte CPU-Auslastung der aktuellen JavaScript-Instanz.', type: 'diagnostic', action: 'cpu_meter' },
  { id: 'F-107', name: 'RAM Heap-Allokation', cat: 'diagnostics', desc: 'Liest belegten und verfuegbaren Arbeitsspeicher (Heap) aus.', type: 'diagnostic', action: 'ram_gauge' },
  { id: 'F-108', name: 'DOM Element Zaehler', cat: 'diagnostics', desc: 'Zaehlt exakte Anzahl aller im HTML gerenderten DOM-Knoten.', type: 'diagnostic', action: 'dom_counter' },
  { id: 'F-109', name: 'Skript-Laufzeit Benchmark', cat: 'diagnostics', desc: 'Fuehrt 100.000 mathematische Operationen aus und stoppt die Zeit.', type: 'diagnostic', action: 'bench_script' },
  { id: 'F-110', name: 'Echtzeit-Latenzpruefung', cat: 'diagnostics', desc: 'Ermittelt aktuelle Roundtrip-Laufzeit zum Server in Millisekunden.', type: 'diagnostic', action: 'latency_test' },
  { id: 'F-111', name: 'Canvas Render FPS Zaehler', cat: 'diagnostics', desc: 'Misst reale Framerate ueber requestAnimationFrame (Soll: 60 FPS).', type: 'diagnostic', action: 'fps_counter' },
  { id: 'F-112', name: 'Web Audio Zustandspruefung', cat: 'diagnostics', desc: 'Validiert Samplerate, Latenz und Kanalanzahl des AudioContext.', type: 'diagnostic', action: 'audio_probe' },
  { id: 'F-113', name: 'LocalStorage Speichermesser', cat: 'diagnostics', desc: 'Berechnet genutzten Speicherplatz im Browser in Kilobytes.', type: 'diagnostic', action: 'ls_size_meter' },
  { id: 'F-114', name: 'Garbage Collection Probe', cat: 'diagnostics', desc: 'Prueft Speicherrueckgewinnung nach aufwaendigen Render-Zyklen.', type: 'diagnostic', action: 'gc_probe' },
  { id: 'F-115', name: 'Event Listener Auditor', cat: 'diagnostics', desc: 'Zaehlt registrierte Klick- und Tastatur-Events im Dokument.', type: 'diagnostic', action: 'listener_audit' },
  { id: 'F-116', name: 'Client OS Kernel Probe', cat: 'diagnostics', desc: 'Liest detaillierte Kernel- und Plattformversion des Clients aus.', type: 'diagnostic', action: 'kernel_probe' },
  { id: 'F-117', name: 'Browser Engine Inspector', cat: 'diagnostics', desc: 'Identifiziert Chromium-, Gecko- oder WebKit-Renderer des Clients.', type: 'diagnostic', action: 'engine_inspect' },
  { id: 'F-118', name: 'Display DPI & Aufloesung', cat: 'diagnostics', desc: 'Liest Aufloesung, Farbtiefe und Skalierungsfaktor (DPI) aus.', type: 'diagnostic', action: 'dpi_gauge' },
  { id: 'F-119', name: 'Battery & Power API Probe', cat: 'diagnostics', desc: 'Prueft Akkustand und Ladezustand des Client-Geraets (falls mobil).', type: 'diagnostic', action: 'battery_probe' },
  { id: 'F-120', name: 'Uhrzeit & Drift-Rechner', cat: 'diagnostics', desc: 'Berechnet zeitliche Abweichung zwischen lokaler Uhr und Server.', type: 'diagnostic', action: 'clock_drift' },
  { id: 'F-121', name: 'CPU-Kerne Zaehler', cat: 'diagnostics', desc: 'Liest navigator.hardwareConcurrency zur Kernanzahl-Erkennung aus.', type: 'diagnostic', action: 'cores_count' },
  { id: 'F-122', name: 'WebGL Grafikbeschleuniger', cat: 'diagnostics', desc: 'Ermittelt genutzte Grafikkarte und WebGL-Unterstuetzung.', type: 'diagnostic', action: 'webgl_probe' },
  { id: 'F-123', name: 'Eingabegeraete Analysator', cat: 'diagnostics', desc: 'Erkennt verfuegbare Maus-, Touch- oder Stift-Eingabegeraete.', type: 'diagnostic', action: 'input_probe' },
  { id: 'F-124', name: 'Media Devices Status', cat: 'diagnostics', desc: 'Prueft ob Audio- und Video-Geraete am System erkannt werden.', type: 'diagnostic', action: 'media_probe' },
  { id: 'F-125', name: 'Responsive Breakpoint Test', cat: 'diagnostics', desc: 'Klassifiziert Display nach Standard-CSS-Klassen (Desktop, Tablet, Mobile).', type: 'diagnostic', action: 'breakpoint_test' },
  { id: 'F-126', name: 'Cookie & Storage Richtlinie', cat: 'diagnostics', desc: 'Ueberprueft ob lokale Speicherung im Browser blockiert wird.', type: 'diagnostic', action: 'cookie_policy' },
  { id: 'F-127', name: 'CSS Renderzeit Benchmark', cat: 'diagnostics', desc: 'Misst Rechenzeit fuer Style-Recalculation bei komplexen Layouts.', type: 'diagnostic', action: 'css_bench' },
  { id: 'F-128', name: 'Font Rendering Check', cat: 'diagnostics', desc: 'Validiert sauberes Laden der System- und Monospace-Schriftarten.', type: 'diagnostic', action: 'font_check' },
  { id: 'F-129', name: 'Web Worker Thread Test', cat: 'diagnostics', desc: 'Prueft ob Multithreading im Hintergrundbrowser unterstuetzt wird.', type: 'diagnostic', action: 'worker_test' },
  { id: 'F-130', name: 'Navigation Timing Dumper', cat: 'diagnostics', desc: 'Gibt Ladezeiten fuer DNS, TCP, Request und DOMContentLoaded aus.', type: 'diagnostic', action: 'nav_timings' },

  // ------------------------------------------------------------------------
  // KATEGORIE 6: DATENVISUALISIERUNG & ANALYTIK (25 FEATURES: F-131 bis F-155)
  // ------------------------------------------------------------------------
  { id: 'F-131', name: 'Client Cluster Uebersicht', cat: 'visualization', desc: 'Visuelle Gruppierung aller aktiven Instanzen nach Version und System.', type: 'tool', action: 'vis_cluster' },
  { id: 'F-132', name: 'Versions-Verteilung Donut', cat: 'visualization', desc: 'Kreisdiagramm ueber den Anteil aktueller vs. veralteter Versionen.', type: 'tool', action: 'vis_donut' },
  { id: 'F-133', name: 'Live Latenz Balkendiagramm', cat: 'visualization', desc: 'Vergleicht Antwortzeiten aller Clients in aufsteigender Folge.', type: 'tool', action: 'vis_latency_bars' },
  { id: 'F-134', name: 'Aktive Nutzer Timeline', cat: 'visualization', desc: 'Zeigt zeitlichen Verlauf der letzten Heartbeat-Verbindungen.', type: 'tool', action: 'vis_timeline' },
  { id: 'F-135', name: 'Update-Adoptionsrate', cat: 'visualization', desc: 'Fortschrittsbalken ueber weltweiten Update-Rollout.', type: 'tool', action: 'vis_adoption' },
  { id: 'F-136', name: 'Befehls-Aktivitaetswelle', cat: 'visualization', desc: 'Animierte Impulswelle bei Eintreffen neuer Admin-Befehle.', type: 'tool', action: 'vis_wave' },
  { id: 'F-137', name: 'System Health Tachometer', cat: 'visualization', desc: 'Kombinierter Gesundheits-Index des gesamten WhatsApp-Tools (0-100%).', type: 'tool', action: 'vis_health_gauge' },
  { id: 'F-138', name: 'Speicherbelegungs-Heatmap', cat: 'visualization', desc: 'Farbcodierte Kacheln ueber Speicherlast der Systemdateien.', type: 'tool', action: 'vis_heatmap' },
  { id: 'F-139', name: 'Fehler-Frequenz Histogramm', cat: 'visualization', desc: 'Haeufigkeit von Warnungen und Systemereignissen.', type: 'tool', action: 'vis_histogram' },
  { id: 'F-140', name: 'Telemetrie Flaechengrafik', cat: 'visualization', desc: 'Flaechendiagramm ueber das Datenvolumen eingehender Heartbeats.', type: 'tool', action: 'vis_area' },
  { id: 'F-141', name: 'Event Stream Sunburst', cat: 'visualization', desc: 'Mehrschichtiges Kreisdiagramm kategorisierter Systemereignisse.', type: 'tool', action: 'vis_sunburst' },
  { id: 'F-142', name: 'Uptime SLA Messuhr', cat: 'visualization', desc: 'Stellt verfuegbare Betriebszeit im Verhaeltnis zu 99.9% dar.', type: 'tool', action: 'vis_sla' },
  { id: 'F-143', name: 'Verbindungs-Radar', cat: 'visualization', desc: 'Kreisfoermige Radar-Darstellung aktiver Client-Knoten.', type: 'tool', action: 'vis_radar' },
  { id: 'F-144', name: 'Sitzungsdauer-Analyse', cat: 'visualization', desc: 'Visualisiert durchschnittliche Verweildauer verbundener Instanzen.', type: 'tool', action: 'vis_session_len' },
  { id: 'F-145', name: 'HWID-Sperren Trendkurve', cat: 'visualization', desc: 'Diagramm ueber historische Zunahme blockierter Hardware-IDs.', type: 'tool', action: 'vis_ban_trend' },
  { id: 'F-146', name: 'Feature Beliebtheits-Matrix', cat: 'visualization', desc: 'Uebersicht der meistgenutzten und am haeufigsten getriggerten Features.', type: 'tool', action: 'vis_popular' },
  { id: 'F-147', name: 'Nachrichten-Durchsatz', cat: 'visualization', desc: 'Kompakte Sparkline ueber Durchsatz versendeter Anrufe & Messages.', type: 'tool', action: 'vis_throughput' },
  { id: 'F-148', name: 'OS Plattform-Verteilung', cat: 'visualization', desc: 'Balkengraph ueber Windows-, macOS- und Linux-Anteile.', type: 'tool', action: 'vis_os_dist' },
  { id: 'F-149', name: 'Latenz-Quartil Boxplot', cat: 'visualization', desc: 'Statistische Streuung der Antwortzeiten in Boxplot-Form.', type: 'tool', action: 'vis_boxplot' },
  { id: 'F-150', name: 'CPU Spikes Streudiagramm', cat: 'visualization', desc: 'Punktdarstellung temporaerer Lastspitzen ueber die Zeit.', type: 'tool', action: 'vis_scatter' },
  { id: 'F-151', name: 'Dateigroessen Treemap', cat: 'visualization', desc: 'Rechteckdiagramm aller 28 Systemdateien proportional zur Dateigroesse.', type: 'tool', action: 'vis_treemap' },
  { id: 'F-152', name: 'Heartbeat Dichtekarte', cat: 'visualization', desc: 'Dichteverteilung empfangener Pings ueber die letzten 10 Minuten.', type: 'tool', action: 'vis_density' },
  { id: 'F-153', name: 'Paketverlust Timeline', cat: 'visualization', desc: 'Zeitleiste temporaer verzoegerter oder ausgefallener Signale.', type: 'tool', action: 'vis_loss_timeline' },
  { id: 'F-154', name: 'Latenz-Ausreisser Radar', cat: 'visualization', desc: 'Hebt Clients mit ungewoehnlich hohen Latenzen grafisch hervor.', type: 'tool', action: 'vis_outliers' },
  { id: 'F-155', name: 'Aktivitaets-Polardiagramm', cat: 'visualization', desc: '360-Grad Polardiagramm der Dashboard-Nutzungsintensitaet.', type: 'tool', action: 'vis_polar' },

  // ------------------------------------------------------------------------
  // KATEGORIE 7: AUDIT & PROTOKOLLE (20 FEATURES: F-156 bis F-175)
  // ------------------------------------------------------------------------
  { id: 'F-156', name: 'Live Event Audit Stream', cat: 'audit', desc: 'Laufendes Protokoll aller Aktionen und Ereignisse im Dashboard.', type: 'audit', action: 'view_audit_stream' },
  { id: 'F-157', name: 'Sicherheits-Ereignis Logger', cat: 'audit', desc: 'Protokolliert alle Sperr-, Entsperr- und Bannvorgaenge chronologisch.', type: 'audit', action: 'security_log' },
  { id: 'F-158', name: 'Administrator Aktionsverlauf', cat: 'audit', desc: 'Lueckenlose Liste aller vom Admin getriggerten Befehle.', type: 'audit', action: 'admin_actions' },
  { id: 'F-159', name: 'Client Statuswechsel Log', cat: 'audit', desc: 'Protokolliert Statusaenderungen (Online, Offline, Wartezeit).', type: 'audit', action: 'client_transitions' },
  { id: 'F-160', name: 'HWID Ban/Unban Historie', cat: 'audit', desc: 'Historischer Nachweis wann welches Geraet gebannt oder entbannt wurde.', type: 'audit', action: 'ban_history' },
  { id: 'F-161', name: 'Downgrade Vorgaenge Log', cat: 'audit', desc: 'Speichert ausgefuehrte Versions-Rueckstufungen mit Zeitstempel.', type: 'audit', action: 'downgrade_log' },
  { id: 'F-162', name: 'Remote Befehls-Audit', cat: 'audit', desc: 'Aufzeichnung aller 40 Steuerungs- und Troll-Befehle.', type: 'audit', action: 'remote_cmd_audit' },
  { id: 'F-163', name: 'Killswitch Verlauf', cat: 'audit', desc: 'Verfolgt jeden Notaus- und Freigabeschritt inklusive Begruendung.', type: 'audit', action: 'killswitch_log' },
  { id: 'F-164', name: 'Broadcast Benachrichtigungen', cat: 'audit', desc: 'Archiv aller veroeffentlichten globalen Ankündigungen.', type: 'audit', action: 'broadcast_archive' },
  { id: 'F-165', name: 'Fehlversuchs-Protokoll', cat: 'audit', desc: 'Protokolliert fehlerhafte API-Aufrufe und abgelehnte Anfragen.', type: 'audit', action: 'failed_auth_log' },
  { id: 'F-166', name: 'Telemetrie Ereignisarchiv', cat: 'audit', desc: 'Archivierte Momentaufnahmen vergangener Telemetriedaten.', type: 'audit', action: 'telemetry_archive' },
  { id: 'F-167', name: 'JSON Audit Export', cat: 'audit', desc: 'Exportiert saemtliche Audit-Protokolle als formatierte JSON-Datei.', type: 'tool', action: 'export_audit_json' },
  { id: 'F-168', name: 'CSV Audit Export', cat: 'audit', desc: 'Erzeugt tabellarischen CSV-Export fuer externe Tabellenprogramme.', type: 'tool', action: 'export_audit_csv' },
  { id: 'F-169', name: 'Audit Log Bereinigung', cat: 'audit', desc: 'Loescht alte Protokolleintraege nach Sicherheitsbestaetigung.', type: 'audit', action: 'clear_audit' },
  { id: 'F-170', name: 'Audit Volltextsuche', cat: 'audit', desc: 'Filtert Protokolleintraege blitzschnell nach Schluesselwoertern.', type: 'audit', action: 'search_audit' },
  { id: 'F-171', name: 'Manipulations-Pruefprotokoll', cat: 'audit', desc: 'Validiert Konsistenz und Zeitstempel aller Log-Eintraege.', type: 'audit', action: 'tamper_log' },
  { id: 'F-172', name: 'Sitzungs-Anomalien Logbuch', cat: 'audit', desc: 'Erfasst unerwartet abbrechende oder doppelte Client-Sitzungen.', type: 'audit', action: 'anomaly_log' },
  { id: 'F-173', name: 'Admin IP-Zugriffsliste', cat: 'audit', desc: 'Zeigt IP-Adressen von denen das Admin-Dashboard aufgerufen wurde.', type: 'audit', action: 'admin_ip_log' },
  { id: 'F-174', name: 'Zeitstempel Integritaet', cat: 'audit', desc: 'Ueberprueft fortlaufende Monotonie aller Protokollzeitstempel.', type: 'audit', action: 'timestamp_audit' },
  { id: 'F-175', name: 'Audit Hash-Ketten Signatur', cat: 'audit', desc: 'Erzeugt SHA-256 Pruefsummenkette zur Revisionssicherheit.', type: 'audit', action: 'hash_chain_audit' },

  // ------------------------------------------------------------------------
  // KATEGORIE 8: DESIGN & THEMES (25 FEATURES: F-176 bis F-200)
  // ------------------------------------------------------------------------
  { id: 'F-176', name: 'Cosmic Neon Theme', cat: 'design', desc: 'Aktiviert leuchtende Cyan- und Violett-Akzente auf schwarzem Grund.', type: 'tool', action: 'theme_neon' },
  { id: 'F-177', name: 'Arctic Silver Theme', cat: 'design', desc: 'Klassisches gebuerstetes Silber und hellgraue Kontrastelemente.', type: 'tool', action: 'theme_silver' },
  { id: 'F-178', name: 'Midnight Nebula Theme', cat: 'design', desc: 'Tiefes Sternenblau mit sanften blauen Schatten-Glows.', type: 'tool', action: 'theme_nebula' },
  { id: 'F-179', name: 'Cyberpunk Kontrast-Modus', cat: 'design', desc: 'Hochkontrast-Design mit goldgelben Elementen fuer maximale Lesbarkeit.', type: 'tool', action: 'theme_cyberpunk' },
  { id: 'F-180', name: 'Monochrome Terminal Theme', cat: 'design', desc: 'Klassischer gruen-auf-schwarz Röhrenmonitor-Look fuer Nostalgiker.', type: 'tool', action: 'theme_terminal' },
  { id: 'F-181', name: 'Emerald Matrix Theme', cat: 'design', desc: 'Tiefgruenes metallisches Design mit smaragdgruenen Status-Pillen.', type: 'tool', action: 'theme_emerald' },
  { id: 'F-182', name: 'Solar Amber Theme', cat: 'design', desc: 'Warmes Bernstein-Design mit edlen Bronze- und Gold-Nuancen.', type: 'tool', action: 'theme_amber' },
  { id: 'F-183', name: 'Deep Navy Classic Theme', cat: 'design', desc: 'Das originale Nacht-System Standard-Design in Dunkelblau.', type: 'tool', action: 'theme_navy' },
  { id: 'F-184', name: 'Frosted Glassmorphism', cat: 'design', desc: 'Verstaerkt Weichzeichner und Transparenz aller Glaskarten.', type: 'tool', action: 'theme_glass' },
  { id: 'F-185', name: 'Schriftgroessen-Skalierung', cat: 'design', desc: 'Schaltet die Textgroesse zwischen Kompakt (12px) und Komfort (14px) um.', type: 'tool', action: 'toggle_font_scale' },
  { id: 'F-186', name: 'Kompakte Tabellendichte', cat: 'design', desc: 'Reduziert Padding in Tabellen fuer maximale Datensicht auf einen Blick.', type: 'tool', action: 'toggle_compact_table' },
  { id: 'F-187', name: 'Ecken-Abrundung Schieber', cat: 'design', desc: 'Passt border-radius aller Karten stufenlos von eckig bis rund an.', type: 'tool', action: 'adjust_radius' },
  { id: 'F-188', name: 'Glow-Intensitaet Schalter', cat: 'design', desc: 'Regelt metallischen Leuchteffekt der Schaltflaechen und Ränder.', type: 'tool', action: 'adjust_glow' },
  { id: 'F-189', name: 'Explorer Sidebar Toggle', cat: 'design', desc: 'Blendet linke Dateiliste fuer maximale Editor-Breite temporaer aus.', type: 'tool', action: 'toggle_sidebar' },
  { id: 'F-190', name: 'Mehrspaltiges Grid Layout', cat: 'design', desc: 'Wechselt zwischen 2- und 3-Spalten Ansicht auf breiten Monitoren.', type: 'tool', action: 'toggle_grid_cols' },
  { id: 'F-191', name: 'Monospace Code-Schrift', cat: 'design', desc: 'Stellt saemtliche Dashboard-Texte auf Cascadia Code Schriftart um.', type: 'tool', action: 'toggle_mono_font' },
  { id: 'F-192', name: 'Barrierefreier Kontrast', cat: 'design', desc: 'Verstaerkt Textkontraste und Umrandungen fuer optimale Sicht.', type: 'tool', action: 'high_contrast' },
  { id: 'F-193', name: 'Animierter Gradient', cat: 'design', desc: 'Sanft pulsierende Hintergrund-Farbverlaeufe fuer lebendiges UI.', type: 'tool', action: 'animated_bg' },
  { id: 'F-194', name: 'Sternenstaub Partikel-FX', cat: 'design', desc: 'Digitaler kosmischer Sternenhimmel im Hintergrund des Dashboards.', type: 'tool', action: 'particle_bg' },
  { id: 'F-195', name: 'Karten 3D-Tilt Effekt', cat: 'design', desc: 'Karten neigen sich perspektivisch bei Mausbewegung darueber.', type: 'tool', action: 'card_tilt' },
  { id: 'F-196', name: 'Header Pillen Style', cat: 'design', desc: 'Waehlt zwischen umrandetem oder voll ausgefuelltem Status-Stil.', type: 'tool', action: 'header_pill_style' },
  { id: 'F-197', name: 'Chrom Metall-Schimmer', cat: 'design', desc: 'Fuegt Buttons eine animierte metallische Glanzkante hinzu.', type: 'tool', action: 'button_sheen' },
  { id: 'F-198', name: 'Custom Brand Titel', cat: 'design', desc: 'Ermoeglicht Anpassen der Hauptueberschrift im Admin-Header.', type: 'tool', action: 'custom_brand' },
  { id: 'F-199', name: 'Theme JSON Profil Export', cat: 'design', desc: 'Exportiert alle vorgenommenen Farbeinstellungen als JSON.', type: 'tool', action: 'export_theme' },
  { id: 'F-200', name: 'Theme Werkseinstellungen', cat: 'design', desc: 'Setzt saemtliche Farb- und Stilanpassungen auf Standard zurueck.', type: 'tool', action: 'reset_theme' },

  // ------------------------------------------------------------------------
  // KATEGORIE 9: AUDIO & SYNTHESIZER (25 FEATURES: F-201 bis F-225)
  // ------------------------------------------------------------------------
  { id: 'F-201', name: 'Retro Startup Chord', cat: 'audio', desc: 'Harmonischer 4-Klang Glocken-Synthesizer (Win95 Klangmuster).', type: 'audio', action: 'sound_win95' },
  { id: 'F-202', name: 'Sci-Fi Laser Blaster', cat: 'audio', desc: 'Abfallender Saegezahn-Frequenzsweep von 950 Hz auf 80 Hz.', type: 'audio', action: 'sound_laser' },
  { id: 'F-203', name: 'Alien UFO Theremin', cat: 'audio', desc: 'Schwebendes Sinus-Vibrato mit 7.5 Hz LFO Frequenzmodulation.', type: 'audio', action: 'sound_alien' },
  { id: 'F-204', name: 'Alarm-Sirene Dreieck', cat: 'audio', desc: 'Dramatischer Dreieckswellen-Heulton in 4 aufeinanderfolgenden Zyklen.', type: 'audio', action: 'sound_siren' },
  { id: 'F-205', name: 'Morse-Code Signal', cat: 'audio', desc: 'Klassische hochfrequente Telegrafie-Pieptoene bei 880 Hz.', type: 'audio', action: 'sound_morse' },
  { id: 'F-206', name: '8-Bit Level Up Jingle', cat: 'audio', desc: 'Aufsteigendes 6-Ton Retro-Arcade Rechteckwellen-Arpeggio.', type: 'audio', action: 'sound_levelup' },
  { id: 'F-207', name: 'Roboter Cyber Chatter', cat: 'audio', desc: 'Neun schnelle pseudozufaellige kybernetische Tonspruenge.', type: 'audio', action: 'sound_robot' },
  { id: 'F-208', name: 'Tempel-Gong Subbass', cat: 'audio', desc: 'Resonanter tiefer Dreieckswellen-Bass bei 110 Hz mit 3.5s Ausklang.', type: 'audio', action: 'sound_gong' },
  { id: 'F-209', name: 'Showmaster Error Buzzer', cat: 'audio', desc: 'Verstimmtes Saegezahn-Doppelton Fehlersignal (120 Hz und 128 Hz).', type: 'audio', action: 'sound_buzzer' },
  { id: 'F-210', name: 'Sieges-Fanfare Trompete', cat: 'audio', desc: 'Viertoniges praegantes Dreieckswellen-Fanfarenmotiv.', type: 'audio', action: 'sound_fanfare' },
  { id: 'F-211', name: 'Sub-Bass 40Hz Dropper', cat: 'audio', desc: 'Ultra-tiefer Bassimpuls fuer Woofer-Test und spuerbare Resonanz.', type: 'audio', action: 'sound_sub40' },
  { id: 'F-212', name: 'Weltraum Echo-Ping', cat: 'audio', desc: 'Nachhallender Hochfrequenz-Impuls mit exponentiellem Echo.', type: 'audio', action: 'sound_echo_ping' },
  { id: 'F-213', name: 'Funken-Arpeggio', cat: 'audio', desc: 'Rasend schnelles 16-Bit Tonleiter-Muster ueber 2 Oktaven.', type: 'audio', action: 'sound_spark_arp' },
  { id: 'F-214', name: 'Analoger Pad-Akkord', cat: 'audio', desc: 'Breiter, warmer Synthesizer-Flaechenklang mit weichem Attack.', type: 'audio', action: 'sound_analog_pad' },
  { id: 'F-215', name: 'Glitch Beat Stotterer', cat: 'audio', desc: 'Rhythmisches digitales Micro-Stottern mit variierender Tonhoehe.', type: 'audio', action: 'sound_glitch_beat' },
  { id: 'F-216', name: 'Digitale Quarzuhr Pieps', cat: 'audio', desc: 'Doppelter praeziser Digitaluhr-Beep bei exakt 2000 Hz.', type: 'audio', action: 'sound_clock_beep' },
  { id: 'F-217', name: 'Arcade Muenzeinwurf', cat: 'audio', desc: 'Glasklarer Zweiton-Klang wie bei historischen Spielautomaten.', type: 'audio', action: 'sound_coin_drop' },
  { id: 'F-218', name: 'Warp-Antrieb Hochlauf', cat: 'audio', desc: 'Kontinuierlich ansteigender Frequenz-Glissando ueber 3 Sekunden.', type: 'audio', action: 'sound_warp_drive' },
  { id: 'F-219', name: 'Sonar U-Boot Impuls', cat: 'audio', desc: 'Tieferer Sinus-Ping mit charakteristischer Unterwasser-Klangfarbe.', type: 'audio', action: 'sound_sonar_ping' },
  { id: 'F-220', name: 'Doppel-Laser Salve', cat: 'audio', desc: 'Zwei kurz getaktete Saegezahn-Blasterstoesse mit Stereo-Gefuehl.', type: 'audio', action: 'sound_dual_laser' },
  { id: 'F-221', name: 'Kristall-Gloeckchen', cat: 'audio', desc: 'Brillantes dreistimmiges Glockenmuster mit langer Abklingzeit.', type: 'audio', action: 'sound_crystal_chime' },
  { id: 'F-222', name: 'Weisses Rausch-Zischen', cat: 'audio', desc: 'Synthetisierter weisser Rauschimpuls mit sanfter Tiefpass-Filterung.', type: 'audio', action: 'sound_white_noise' },
  { id: 'F-223', name: 'Resonanz Filter-Sweep', cat: 'audio', desc: 'Klassischer Synthesizer-Sweep von dumpf nach schneidend scharf.', type: 'audio', action: 'sound_filter_sweep' },
  { id: 'F-224', name: 'Dramatischer Sub-Impact', cat: 'audio', desc: 'Wuchtiger filmischer Tiefton-Treffer mit sanftem Bass-Decay.', type: 'audio', action: 'sound_sub_impact' },
  { id: 'F-225', name: 'Harmonische Dur-Folge', cat: 'audio', desc: 'Drei nacheinander klingende Dur-Akkorde zur Erfolgsbestaetigung.', type: 'audio', action: 'sound_triad_chords' },

  // ------------------------------------------------------------------------
  // KATEGORIE 10: UI-EFFEKTE & TROLLS (25 FEATURES: F-226 bis F-250)
  // ------------------------------------------------------------------------
  { id: 'F-226', name: 'Fake Hacker Terminal', cat: 'trolls', desc: 'Hollywood-artiges Terminal-Overlay mit fliessendem Root-Override Text.', type: 'remote', action: 'troll_hacker' },
  { id: 'F-227', name: 'Lustiger Fake BSOD', cat: 'trolls', desc: 'Blauer Windows-Spaesschen-Bildschirm mit TROLL_EXCEPTION_NOT_SERIOUS.', type: 'remote', action: 'troll_bsod' },
  { id: 'F-228', name: 'Ausweichender Senden-Button', cat: 'trolls', desc: 'Button weicht fuer 15 Sekunden schelmisch dem Mauszeiger aus.', type: 'remote', action: 'troll_evasive' },
  { id: 'F-229', name: 'Bildschirm 180° Kopfstand', cat: 'trolls', desc: 'Dreht die Benutzeroberflaeche des Clients fuer 8 Sekunden auf den Kopf.', type: 'remote', action: 'troll_upsidedown' },
  { id: 'F-230', name: 'Fake 9999 MB Update-Balken', cat: 'trolls', desc: 'Fortschrittsbalken laedt dramatisch geheime Quanten-Optimierungen.', type: 'remote', action: 'troll_fake_update' },
  { id: 'F-231', name: 'Spiegel-Schrift (RTL Text)', cat: 'trolls', desc: 'Alle Ueberschriften und Buttons werden fuer 10 Sekunden rueckwaerts dargestellt.', type: 'remote', action: 'troll_reverse_text' },
  { id: 'F-232', name: 'Schwerkraft-Rutscher', cat: 'trolls', desc: 'Fenster-Elemente sacken mit sanftem Bounce-Effekt nach unten ab.', type: 'remote', action: 'troll_gravity' },
  { id: 'F-233', name: 'Popcorn Blaeschen Plopp', cat: 'trolls', desc: '16 bunte Popcorn-Blasen steigen im Client-Fenster auf und zerplatzen.', type: 'remote', action: 'troll_popcorn' },
  { id: 'F-234', name: 'Selbstzerstoerungs-Countdown', cat: 'trolls', desc: 'Dramatischer 5-Sekunden Alarm-Countdown mit Nur-Spass Entwarnung.', type: 'remote', action: 'troll_selfdestruct' },
  { id: 'F-235', name: 'Custom Toast Banner', cat: 'trolls', desc: 'Verschickt eine frei definierbare Nachricht als Toast-Popup an den Client.', type: 'remote', action: 'troll_custom_toast' },
  { id: 'F-236', name: 'Matrix Code Rain', cat: 'trolls', desc: 'Fluessige gruene Datenkaskade ueber den gesamten Bildschirm fuer 8s.', type: 'remote', action: 'effect_matrix' },
  { id: 'F-237', name: 'Disco Light Randfeuer', cat: 'trolls', desc: 'Pulsierende bunte Randbeleuchtung um den Bildschirm fuer 6s.', type: 'remote', action: 'effect_disco' },
  { id: 'F-238', name: 'Tarnkappe (Stealth Dim)', cat: 'trolls', desc: 'Dunkelt das Fenster auf 18% Helligkeit ab fuer 10 Sekunden.', type: 'remote', action: 'effect_stealth' },
  { id: 'F-239', name: 'Farben Invertieren Negativ', cat: 'trolls', desc: 'Dreht alle Farben und Grafiken fuer 7s ins genaue Negativ um.', type: 'remote', action: 'effect_invert' },
  { id: 'F-240', name: 'Horizontaler Spiegel-Modus', cat: 'trolls', desc: 'Spiegelt die Benutzeroberflaeche des Clients horizontal fuer 8s.', type: 'remote', action: 'effect_mirror' },
  { id: 'F-241', name: 'Erdbeben Screen Shake', cat: 'trolls', desc: 'Sanftes, verblueffendes Wackeln des gesamten Tool-Fensters fuer 4s.', type: 'remote', action: 'effect_shake' },
  { id: 'F-242', name: 'Slow-Motion Klickmodus', cat: 'trolls', desc: 'Stark verlangsamte Uebergaenge und Klick-Animationen fuer 12s.', type: 'remote', action: 'effect_slowmo' },
  { id: 'F-243', name: 'Digitales Konfetti-Feuerwerk', cat: 'trolls', desc: 'Bunte digitale Konfetti-Partikel regnen ueber den Bildschirm.', type: 'remote', action: 'effect_confetti' },
  { id: 'F-244', name: 'CRT Retro Scanlines Glitch', cat: 'trolls', desc: 'Scanline-Streifen und Flimmern wie auf alten Roehrenmonitoren.', type: 'remote', action: 'effect_crt' },
  { id: 'F-245', name: 'Nebel- & Weichzeichner', cat: 'trolls', desc: 'Sanfter Blur-Schleier ueber die Benutzeroberflaeche fuer 6s.', type: 'remote', action: 'effect_blur_fog' },
  { id: 'F-246', name: 'Mauszeiger Funken-Schweif', cat: 'trolls', desc: 'Hinterlaesst digitale Leuchtpartikel beim Bewegen der Maus.', type: 'tool', action: 'mouse_sparks' },
  { id: 'F-247', name: 'Wasser-Wellen Ripple FX', cat: 'trolls', desc: 'Simuliert sanfte Wasserwellen auf der Oberflaeche bei Klicks.', type: 'tool', action: 'water_ripple' },
  { id: 'F-248', name: 'Regenbogen Text-Glitch', cat: 'trolls', desc: 'Ueberschriften schillern fuer kurze Zeit in wechselnden Neonfarben.', type: 'tool', action: 'rainbow_text' },
  { id: 'F-249', name: 'Fake Geister-Tippen', cat: 'trolls', desc: 'Simuliert automatische Tastaturanschlaege im Notizfeld.', type: 'tool', action: 'ghost_type' },
  { id: 'F-250', name: 'Button Tausch-Zauber', cat: 'trolls', desc: 'Tauscht fuer 8 Sekunden kurzzeitig zwei Buttons die Position.', type: 'tool', action: 'button_swap' }
];

// Als globales Objekt fuer admin.js verfuegbar machen
window.MASTER_FEATURES_CATALOG = MASTER_FEATURES_CATALOG;
